#!/usr/bin/env python3
"""finops-init — interactive setup for Commons FinOps local context.

Prompts for the highest-value fields, writes context.yaml at the repo root,
and adds it to .gitignore so private thresholds and org details are never
committed. Advanced users can hand-edit the yaml directly.

Usage:
    python ai/init.py
    python ai/init.py --non-interactive           # use defaults, still writes context.yaml
    python ai/init.py --overwrite                 # replace existing context.yaml
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EXAMPLE = REPO_ROOT / "ai" / "context.example.yaml"
TARGET = REPO_ROOT / "context.yaml"
GITIGNORE = REPO_ROOT / ".gitignore"


def prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"  {label}{suffix}: ").strip()
    return val or default


def main() -> int:
    ap = argparse.ArgumentParser(description="Initialize a Commons FinOps context.yaml")
    ap.add_argument("--non-interactive", action="store_true", help="Skip prompts, copy example verbatim")
    ap.add_argument("--overwrite", action="store_true", help="Replace an existing context.yaml")
    args = ap.parse_args()

    if TARGET.exists() and not args.overwrite:
        print(f"context.yaml already exists at {TARGET}. Pass --overwrite to replace.")
        return 1

    if not EXAMPLE.exists():
        print(f"ERROR: example not found at {EXAMPLE}", file=sys.stderr)
        return 1

    if args.non_interactive:
        shutil.copy2(EXAMPLE, TARGET)
        print(f"Wrote {TARGET} from example (non-interactive).")
    else:
        print("\nCommons FinOps — one-time setup")
        print("=" * 60)
        print("Answer a few questions to generate your context.yaml. Press")
        print("Enter to accept the default. You can edit the file later.\n")

        print("Organization")
        org_name = prompt("Short name", "Example Sponsor")
        legal_name = prompt("Legal name", f"{org_name}, Inc.")
        state = prompt("State of incorporation", "Delaware")
        ein = prompt("EIN (leave blank if none)", "12-3456789")
        address = prompt("Address", "123 Main Street, Anytown, ST 12345")

        print("\nApproval thresholds (USD, press Enter for common defaults)")
        dfo_review = prompt("DFO review above", "$10,000")
        board_secondary = prompt("Board President secondary above", "$15,000")
        competitive_bids = prompt("Competitive bids required above", "$30,000")
        board_exception = prompt("Full Board exception above", "$100,000")
        deviation = prompt("Budget-deviation prior approval above", "$20,000")
        capitalization = prompt("Capitalization threshold", "$5,000")

        print("\nPlatforms (leave blank to keep generic prose)")
        gl = prompt("General ledger", "QuickBooks Online")
        fiscal_host = prompt("Fiscal-sponsorship platform", "Open Collective")
        crypto_sub = prompt("Digital-asset subledger", "")
        crypto_custodian = prompt("Crypto custodian", "")
        card_processor = prompt("Card / donation processor", "Stripe")

        print("\nRates")
        host_fee = prompt("Fiscal-sponsorship (host) fee", "10%")

        content = f"""# Generated by finops-init on first run. Edit freely.
# For the full schema and inline documentation, see ai/context.example.yaml
org:
  name: "{org_name}"
  legal_name: "{legal_name}"
  legal_name_upper: "{legal_name.upper()}"
  state: "{state}"
  ein: "{ein}"
  address: "{address}"

thresholds:
  dfo_review: "{dfo_review}"
  board_secondary: "{board_secondary}"
  competitive_bids: "{competitive_bids}"
  board_exception: "{board_exception}"
  deviation: "{deviation}"
  capitalization: "{capitalization}"
  software_review: "$2,500"
  s1099_min: "$600"
  line_item_review: "$500"

windows:
  reimbursement: "30 days"
  reimbursement_adj: "30-day"
  explanation: "60 days"
  dfo_approval: "90 days"
  miscode_flag: "30 days"
  crypto_conversion: "5 business days"
  crypto_conversion_cap: "Five business days"

platforms:
  gl: "{gl}"
  fiscal_host: "{fiscal_host}"
  crypto_sub: "{crypto_sub}"
  crypto_custodian: "{crypto_custodian}"
  card_processor: "{card_processor}"
  external_accountant: ""

rates:
  host_fee: "{host_fee}"

local:
  notes: |
    Add any organization-specific notes here.
  chart_of_accounts: {{}}
  projects: []
  people:
    dfo: ""
    executive_director: ""
    board_president: ""

schema_version: "0.1"
"""
        TARGET.write_text(content, encoding="utf-8")
        print(f"\nWrote {TARGET}")

    # Ensure context.yaml is gitignored
    if GITIGNORE.exists():
        gi = GITIGNORE.read_text(encoding="utf-8")
    else:
        gi = ""
    if "context.yaml" not in gi:
        with GITIGNORE.open("a", encoding="utf-8") as f:
            if gi and not gi.endswith("\n"):
                f.write("\n")
            f.write("\n# Local Commons FinOps context (created by finops-init)\ncontext.yaml\ncontext.yml\nrendered/\n")
        print(f"Added context.yaml to {GITIGNORE.name}")

    print("\nNext steps:")
    print("  1. Review context.yaml and fill in anything you skipped.")
    print("  2. Render the policies:")
    print("     python ai/render.py 'templates/policies/*.md'")
    print("  3. Or point your AI assistant at the MCP server:")
    print("     see ai/mcp-server/README.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
